/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "ApiFunction": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "ApiKey": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "ApiRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "Auth": {
      "type": "sst.aws.Auth"
      "url": string
    }
    "BudgetAlertSNS": {
      "arn": string
      "type": "sst.aws.SnsTopic"
    }
    "Cache": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Dashboard": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "DominantColor": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Email": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "Follow": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "GoogleClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Lists": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "MdblistApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MetricsApiAggregated": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "MetricsDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "MetricsQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "MetricsRaw": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "MetricsWebVitalsAggregated": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "PreferredImages": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "ScrobbleQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "SessionSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TmdbApiAccessToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TmdbApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Users": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "ValidateWatchedStatusQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "Watched": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "WebhookTokens": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}