/// <reference path="../.sst/platform/config.d.ts" />

import { execSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { apiRouter } from './api';
import { auth } from './auth';
import { domain } from './dns';
import * as secrets from './secrets';

const PROJECT_NAME = 'tvseries-web';

// Feature flag - enable after verifying Vercel deployment works
const ENABLE_CUSTOM_DOMAINS = false;

// In dev mode, skip Vercel deployment - run Next.js dev server locally
if ($dev) {
  // Generate .env.local with the API/Auth URLs
  $resolve([
    apiRouter.url,
    auth.url,
    secrets.apiKeyRandom.result,
    secrets.sessionSecret.value,
  ]).apply(([apiUrl, authUrl, apiKey, secretKey]) => {
    const envContent = `# Auto-generated by SST dev - do not commit
API_KEY=${apiKey}
API_URL=${apiUrl}
AUTH_URL=${authUrl}
SECRET_KEY=${secretKey}
SITE_URL=http://localhost:3000
`;
    const envPath = path.join(process.cwd(), 'apps/web/.env.local');
    fs.writeFileSync(envPath, envContent);
    console.log(`|  Generated ${envPath} with dev environment variables`);
  });

  // Run Next.js dev server with custom title
  new sst.x.DevCommand('Website', {
    dev: {
      command: 'next dev',
      directory: 'apps/web',
      title: 'Website',
    },
  });
}

export const web = $dev
  ? { url: 'http://localhost:3000' }
  : (() => {
      const gitHash =
        process.env.GITHUB_SHA ||
        execSync('git rev-parse --short HEAD').toString().trim();

      const gitBranch =
        process.env.GITHUB_HEAD_REF ||
        process.env.GITHUB_REF_NAME ||
        execSync('git rev-parse --abbrev-ref HEAD').toString().trim();

      const projectSettings = {
        buildCommand: 'pnpm run build',
        framework: 'nextjs',
        installCommand: 'pnpm install --frozen-lockfile --ignore-scripts',
        outputDirectory: '.next',
        rootDirectory: 'apps/web',
      };

      // Create the Vercel project
      // Pulumi state tracks this resource - subsequent deploys won't recreate it
      const project = new vercel.Project('WebProject', {
        buildCommand: projectSettings.buildCommand,
        framework: 'nextjs',
        gitRepository: {
          repo: 'koenoe/tvseri.es',
          type: 'github',
        },
        installCommand: projectSettings.installCommand,
        name: PROJECT_NAME,
        outputDirectory: projectSettings.outputDirectory,
        rootDirectory: projectSettings.rootDirectory,
      });

      // Create deployment
      const deployment = new vercel.Deployment('WebDeployment', {
        environment: {
          API_KEY: secrets.apiKeyRandom.result,
          API_URL: apiRouter.url,
          AUTH_URL: auth.url,
          SECRET_KEY: secrets.sessionSecret.value,
          SITE_URL: `https://${domain}`,
        },
        production: $app.stage === 'production',
        projectId: project.id,
        projectSettings,
        ref: $app.stage === 'production' ? gitHash : gitBranch,
      });

      // Custom domains - enable after testing basic Vercel deployment
      if (ENABLE_CUSTOM_DOMAINS) {
        // Production domain
        if ($app.stage === 'production') {
          new vercel.ProjectDomain('WebDomain', {
            domain: 'tvseri.es',
            projectId: project.id,
          });

          new vercel.ProjectDomain('WebDomainWww', {
            domain: 'www.tvseri.es',
            projectId: project.id,
            redirect: 'tvseri.es',
          });
        }

        // Preview domain alias (e.g., pr-123.dev.tvseri.es)
        if ($app.stage !== 'production' && $app.stage !== 'dev') {
          // Add the subdomain to the project
          new vercel.ProjectDomain('WebPreviewDomain', {
            domain: `${$app.stage}.dev.tvseri.es`,
            projectId: project.id,
          });

          // Alias the deployment to the custom domain
          new vercel.Alias('WebPreviewAlias', {
            alias: `${$app.stage}.dev.tvseri.es`,
            deploymentId: deployment.id,
          });
        }
      }

      return deployment;
    })();
