/// <reference path="../.sst/platform/config.d.ts" />

import { execSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { apiRouter } from './api';
import { auth } from './auth';
import { domain } from './dns';
import * as secrets from './secrets';

const PROJECT_NAME = 'tvseries-web';

// Feature flag - enable after verifying Vercel deployment works
const ENABLE_CUSTOM_DOMAINS = false;

// In dev mode, skip Vercel deployment - run Next.js dev server locally
if ($dev) {
  // Generate .env.local with the API/Auth URLs
  $resolve([
    apiRouter.url,
    auth.url,
    secrets.apiKeyRandom.result,
    secrets.sessionSecret.value,
  ]).apply(([apiUrl, authUrl, apiKey, secretKey]) => {
    const envContent = `# Auto-generated by SST dev - do not commit
API_KEY=${apiKey}
API_URL=${apiUrl}
AUTH_URL=${authUrl}
SECRET_KEY=${secretKey}
SITE_URL=http://localhost:3000
`;
    const envPath = path.join(process.cwd(), 'apps/web/.env.local');
    fs.writeFileSync(envPath, envContent);
    console.log(`|  Generated ${envPath} with dev environment variables`);
  });

  // Run Next.js dev server with custom title
  new sst.x.DevCommand('Website', {
    dev: {
      command: 'next dev',
      directory: 'apps/web',
      title: 'Website',
    },
  });
}

export const web = $dev
  ? { url: 'http://localhost:3000' }
  : (() => {
      // Create the Vercel project - Pulumi manages this resource
      const project = new vercel.Project('WebProject', {
        framework: 'nextjs',
        name: PROJECT_NAME,
        // rootDirectory is critical for monorepo prebuilt deployments
        // See: https://github.com/vercel/vercel/issues/8794
        rootDirectory: 'apps/web',
      });

      // Build the app with env vars from SST resources, then deploy
      const deploymentUrl = $resolve([
        apiRouter.url,
        auth.url,
        secrets.apiKeyRandom.result,
        secrets.sessionSecret.value,
        project.id,
      ]).apply(([apiUrl, authUrl, apiKey, secretKey, projectId]) => {
        const siteUrl = `https://${domain}`;
        // Vercel CLI must run from monorepo root with rootDirectory set to apps/web
        // See: https://github.com/vercel/vercel/issues/8794
        const monorepoRoot = process.cwd();
        const isProduction = $app.stage === 'production';
        const environment = isProduction ? 'production' : 'preview';
        const token = process.env.VERCEL_API_TOKEN!;

        // Pull Vercel project settings
        console.log('|  Pulling Vercel project settings...');
        execSync(
          `npx vercel pull --yes --environment=${environment} --token=${token}`,
          {
            cwd: monorepoRoot,
            env: {
              ...process.env,
              VERCEL_PROJECT_ID: projectId,
            },
            stdio: 'inherit',
          },
        );

        // Run vercel build from monorepo root (uses rootDirectory from project settings)
        console.log('|  Building Next.js app with Vercel CLI...');
        execSync(
          `npx vercel build${isProduction ? ' --prod' : ''} --token=${token}`,
          {
            cwd: monorepoRoot,
            env: {
              ...process.env,
              API_KEY: apiKey,
              API_URL: apiUrl,
              AUTH_URL: authUrl,
              SECRET_KEY: secretKey,
              SITE_URL: siteUrl,
              VERCEL_PROJECT_ID: projectId,
            },
            stdio: 'inherit',
          },
        );

        // Deploy using CLI with --archive=tgz for proper monorepo support
        // This handles node_modules bundling better than the Pulumi resource
        console.log('|  Deploying to Vercel...');
        const envFlags = [
          `-e API_KEY=${apiKey}`,
          `-e API_URL=${apiUrl}`,
          `-e AUTH_URL=${authUrl}`,
          `-e SECRET_KEY=${secretKey}`,
          `-e SITE_URL=${siteUrl}`,
        ].join(' ');
        const deployOutput = execSync(
          `npx vercel deploy --prebuilt${isProduction ? ' --prod' : ''} --archive=tgz ${envFlags} --token=${token}`,
          {
            cwd: monorepoRoot,
            encoding: 'utf-8',
            env: {
              ...process.env,
              VERCEL_PROJECT_ID: projectId,
            },
          },
        );

        // vercel deploy outputs the deployment URL to stdout
        const url = deployOutput.trim();
        console.log(`|  Deployed to ${url}`);
        return url;
      });

      // Custom domains - enable after testing basic Vercel deployment
      if (ENABLE_CUSTOM_DOMAINS) {
        // Production domain
        if ($app.stage === 'production') {
          new vercel.ProjectDomain('WebDomain', {
            domain: 'tvseri.es',
            projectId: project.id,
          });

          new vercel.ProjectDomain('WebDomainWww', {
            domain: 'www.tvseri.es',
            projectId: project.id,
            redirect: 'tvseri.es',
          });
        }

        // Preview domain alias (e.g., pr-123.dev.tvseri.es)
        // Note: Can't use vercel.Alias here since we don't have a Pulumi deployment resource
        // The CLI deployment already creates the URL we need
      }

      return {
        url: deploymentUrl,
      };
    })();
