/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/// <reference types="vite/client" />
interface ImportMetaEnv {
  readonly API_PROXY: string
  readonly API_USE_MOCK_DATA: string
  readonly VITE_API_URL: string
  readonly VITE_AUTH_URL: string
}
interface ImportMeta {
  readonly env: ImportMetaEnv
}